PORT: 3000
MON_PORT: 8080
DEFINITIONS_GRPC_ADDR: localhost:8086
TOKEN_EXCHANGE_JWK_KEY_SET_URL: http://127.0.0.1:5556/dex/keys
TOKEN_EXCHANGE_ISSUER_URL: http://127.0.0.1:5556/dex
VEHICLE_NFT_ADDRESS: 0x90c4d6113ec88dd4bdf12f26db2b3998fd13a144
TELEMETRY_URL: http://localhost:8087
FINGERPRINT_BUCKET: dimo-network-fingerprint-dev
FINGERPRINT_DATA_TYPE: "FP_v0.0.1"
PARQUET_BUCKET: dimo-iceberg-prod
VINVC_DATA_TYPE: "VINVCv0.0"
IDENTITY_API_URL: idenity-api.dimo.zone
VIN_ISSUER_PRIVATE_KEY: 3f1e1d4c2b1a59683f1e1d4c2b1a59683f1e1d4c2b1a59683f1e1d4c2b1a5968 # Not a real key
DIMO_REGISTRY_CHAIN_ID: 137
DIS_URL: https://dis.dimo.zone
DEX_URL: https://auth.dimo.zone
DEV_LICENSE: 1234567890
FETCH_GRPC_ADDR: localhost:8085